version: "3"

# Config file for compose, a tool that allows for easily managing multiple docker containers.
# https://docs.docker.com/compose/

services:
    surreal:
        # not :nightly because doing that once caused failures when graph linking
        # and also caused errors with query parameters
        image: surrealdb/surrealdb:v1.3.0
        ports:
            - 8000:8000
        restart: unless-stopped
        volumes:
            - ./data/surreal:/database
        command:
            - start
            - --log=trace
            - --user=root
            - --pass=root
            - --allow-scripting
            - file:database
    centrifugo:
        container_name: centrifugo
        image: centrifugo/centrifugo:v5
        volumes:
            - ./centrifugo.yml:/centrifugo/centrifugo.yml
        command: centrifugo -c centrifugo.yml
        ports:
            - 7999:8000
        restart: unless-stopped
        ulimits:
            nofile:
                soft: 65535
                hard: 65535
