name: Deploy

# Github action to deploy the website to the server.

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Deploy to Server
              uses: fifsky/ssh-action@master
              with:
                  command: |
                      bash
                      cd mercuryv2 && git restore . && git pull && aftman install && lune run ./corescripts/compile.luau && bun --bun prod && pm2 start --interpreter ~/.bun/bin/bun build && cd / && caddy reload && exit
                      exit
                  host: ${{ secrets.HOST }}
                  port: ${{ secrets.PORT }}
                  user: ${{ secrets.USER }}
                  pass: ${{ secrets.PASS }}
                  args: -tt
